const defaultProducts = [
  { id: 1, name: 'Halo desk lamp', category: 'desk', price: 89, image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=85', description: 'A sculptural light with a warm dimmer and a cool silhouette.' },
  { id: 2, name: 'Orbit headphones', category: 'audio', price: 149, image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=85', description: 'Immersive wireless audio with a soft-touch finish for long listening.' },
  { id: 3, name: 'Signal sling', category: 'carry', price: 78, image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=85', description: 'A compact everyday carry with room for your essentials and a little more.' },
  { id: 4, name: 'Grid notebook', category: 'desk', price: 24, image: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=900&q=85', description: 'Heavyweight recycled paper for ideas that deserve to stay.' },
  { id: 5, name: 'Pulse speaker', category: 'audio', price: 118, image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=85', description: 'Room-filling sound in a small, considered form.' },
  { id: 6, name: 'Vector tote', category: 'carry', price: 42, image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=900&q=85', description: 'A sturdy canvas tote with an architectural pocket system.' },
  { id: 7, name: 'Keylight mini', category: 'desk', price: 55, image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=900&q=85', description: 'A pocket-sized beam for late nights and bright ideas.' },
  { id: 8, name: 'Loop earbuds', category: 'audio', price: 96, image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=900&q=85', description: 'Lightweight wireless listening with a clean, low-profile case.' }
];
let products = JSON.parse(localStorage.getItem('novaProducts')) || defaultProducts;
let cart = JSON.parse(localStorage.getItem('novaCart')) || [];
let activeCategory = 'all';
let query = '';
const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
function money(value) { return `$${Number(value).toFixed(0)}`; }
function save() { localStorage.setItem('novaProducts', JSON.stringify(products)); localStorage.setItem('novaCart', JSON.stringify(cart)); }
function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2200); }
function visibleProducts() { return products.filter(product => (activeCategory === 'all' || product.category === activeCategory) && `${product.name} ${product.description}`.toLowerCase().includes(query.toLowerCase())); }
function renderProducts() { const list = visibleProducts(); $('#emptyProducts').classList.toggle('hidden', list.length > 0); $('#productGrid').innerHTML = list.map(product => `<article class="product-card"><button class="product-image" data-view="${product.id}" aria-label="View ${product.name}"><img src="${product.image}" alt="${product.name}" loading="lazy" /></button><div class="product-info"><div><h3 class="product-name">${product.name}</h3><p class="product-meta">${product.category} / <button class="add-button" data-add="${product.id}">Add to bag</button></p></div><span class="product-price">${money(product.price)}</span></div></article>`).join(''); }
function cartCount() { return cart.reduce((total, item) => total + item.quantity, 0); }
function cartTotal() { return cart.reduce((total, item) => total + item.quantity * item.price, 0); }
function renderCart() { $('#cartCount').textContent = cartCount(); $('#cartTotal').textContent = money(cartTotal()); $('#cartItems').innerHTML = cart.length ? cart.map(item => `<div class="cart-row"><img src="${item.image}" alt="${item.name}" /><div><h4>${item.name}</h4><p>${money(item.price)} each</p><div class="qty-controls"><button data-quantity="${item.id}" data-change="-1">−</button><span>${item.quantity}</span><button data-quantity="${item.id}" data-change="1">+</button></div></div><button class="remove-item" data-remove="${item.id}">Remove</button></div>`).join('') : '<p class="empty-state">Your bag is waiting for a signal.</p>'; }
function addToCart(id) { const product = products.find(item => item.id === id); const existing = cart.find(item => item.id === id); if (existing) existing.quantity += 1; else cart.push({ ...product, quantity: 1 }); save(); renderCart(); showToast(`${product.name} added to bag`); }
function openDrawer() { $('#cartDrawer').classList.add('open'); $('#cartDrawer').setAttribute('aria-hidden', 'false'); $('#drawerBackdrop').classList.remove('hidden'); }
function closeDrawer() { $('#cartDrawer').classList.remove('open'); $('#cartDrawer').setAttribute('aria-hidden', 'true'); $('#drawerBackdrop').classList.add('hidden'); }
function showProduct(id) { const product = products.find(item => item.id === id); $('#productDetail').innerHTML = `<div class="detail-grid"><img src="${product.image}" alt="${product.name}" /><div><p class="kicker">${product.category} object</p><h2>${product.name}</h2><p>${product.description}</p><strong>${money(product.price)}</strong><br /><button class="button button-neon" data-detail-add="${product.id}" style="margin-top:24px">Add to bag →</button></div></div>`; $('#productDialog').showModal(); }
$('#categoryFilters').addEventListener('click', event => { const button = event.target.closest('[data-category]'); if (!button) return; activeCategory = button.dataset.category; $$('.filter-chip').forEach(item => item.classList.toggle('active', item === button)); renderProducts(); });
$('#searchInput').addEventListener('input', event => { query = event.target.value; renderProducts(); });
$('#productGrid').addEventListener('click', event => { const add = event.target.closest('[data-add]'); const view = event.target.closest('[data-view]'); if (add) addToCart(Number(add.dataset.add)); if (view) showProduct(Number(view.dataset.view)); });
$('#cartButton').addEventListener('click', openDrawer); $('#closeCart').addEventListener('click', closeDrawer); $('#drawerBackdrop').addEventListener('click', closeDrawer);
$('#cartItems').addEventListener('click', event => { const remove = event.target.closest('[data-remove]'); const quantity = event.target.closest('[data-quantity]'); if (remove) cart = cart.filter(item => item.id !== Number(remove.dataset.remove)); if (quantity) { const item = cart.find(entry => entry.id === Number(quantity.dataset.quantity)); item.quantity += Number(quantity.dataset.change); if (item.quantity < 1) cart = cart.filter(entry => entry.id !== item.id); } save(); renderCart(); });
$('#productDetail').addEventListener('click', event => { const button = event.target.closest('[data-detail-add]'); if (button) { addToCart(Number(button.dataset.detailAdd)); $('#productDialog').close(); } });
$('#checkoutButton').addEventListener('click', () => { if (!cart.length) return showToast('Your bag is empty'); cart = []; save(); renderCart(); closeDrawer(); $('#successDialog').showModal(); });
$('#adminForm').addEventListener('submit', event => { event.preventDefault(); const product = { id: Date.now(), name: $('#adminName').value.trim(), price: Number($('#adminPrice').value), category: $('#adminCategory').value, image: $('#adminImage').value.trim() || 'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=900&q=85', description: 'A new addition to the NOVA signal.' }; products.unshift(product); save(); renderProducts(); event.target.reset(); showToast('Product added to the catalog'); });
$('#loginButton').addEventListener('click', () => $('#loginDialog').showModal()); $('#loginForm').addEventListener('submit', event => { event.preventDefault(); const valid = $('#username').value === 'shyam' && $('#password').value === 'shyam123'; $('#loginError').classList.toggle('hidden', valid); if (valid) { $('#loginDialog').close(); showToast('Signed in as shyam'); } });
$$('[data-close-dialog]').forEach(button => button.addEventListener('click', () => button.closest('dialog').close()));
renderProducts(); renderCart();
